/*
 * Ability Options LLC App
 * This servers hosts API needed for Ability Options LLC.
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.ability.model;

import java.time.LocalDate;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

@AllArgsConstructor
@NoArgsConstructor
@Data
@ToString
@JsonInclude(Include. NON_NULL)
public class Availability {

    @JsonProperty("availability_id")
    private Integer availabilityId = null;

    @JsonProperty("work_hours_per_week")
    private String workHoursPerWeek = null;

    @JsonProperty("work_on_weekends")
    private String workOnWeekends = null;

    @JsonProperty("work_on_nights")
    private String workOnNights = null;

    @JsonProperty("legally_authorized_to_work")
    private String legallyAuthorizedToWork = null;

    @JsonProperty("available_start_date")
    @JsonFormat(pattern = "yyyy-MM-dd")
    private LocalDate availableStartDate = null;

    @JsonProperty("times_whem_not_available_work")
    private String timesWhemNotAvailableWork = null;

    @JsonProperty("employment_desired")
    private String employmentDesired = null;

}
