/*
 * Ability Options LLC App
 * This servers hosts API needed for Ability Options LLC.
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.ability.model;

import com.fasterxml.jackson.annotation.JsonProperty;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

@AllArgsConstructor
@NoArgsConstructor
@Data
@ToString
public class Education {

    @JsonProperty("education_id")
    private Integer educationId = null;

    @JsonProperty("school_type")
    private String schoolType = null;

    @JsonProperty("name")
    private String name = null;

    @JsonProperty("city")
    private String city = null;

    @JsonProperty("state")
    private String state = null;

    @JsonProperty("country")
    private String country = null;

    @JsonProperty("level_completed")
    private String levelCompleted = null;

    @JsonProperty("degree")
    private String degree = null;

    @JsonProperty("major")
    private String major = null;

    @JsonProperty("degree_certificate_path")
    private String degreeCertificatePath = null;

}
