/*
 * Ability Options LLC App
 * This servers hosts API needed for Ability Options LLC.
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.ability.model;

import java.time.LocalDate;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Employee work experience object
 */
@JsonInclude(Include. NON_NULL)
@AllArgsConstructor
@NoArgsConstructor
@Data
@ToString
public class Experience {
    @JsonProperty("experience_id")
    private Integer experienceId = null;

    @JsonProperty("company")
    private String company = null;

    @JsonProperty("start_date")
    @JsonFormat(pattern="yyyy-MM-dd")
    private LocalDate startDate = null;

    @JsonProperty("end_date")
    @JsonFormat(pattern="yyyy-MM-dd")
    private LocalDate endDate = null;

    @JsonProperty("reason_left")
    private String reasonLeft = null;

    @JsonProperty("is_current_company")
    private Boolean isCurrentCompany = null;

    @JsonProperty("manager_name")
    private String managerName = null;

    @JsonProperty("phone_number")
    private Phone phoneNumber = null;

    @JsonProperty("job_title")
    private String jobTitle = null;

    @JsonProperty("can_we_contact")
    private Boolean canWeContact = null;

  
}
