/*
 * Ability Options LLC App
 * This servers hosts API needed for Ability Options LLC.
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.ability.model;

import com.fasterxml.jackson.annotation.JsonProperty;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;
@AllArgsConstructor
@NoArgsConstructor
@Data
@ToString
public class Reference {
    
    @JsonProperty("reference_id")
    private Integer referenceId = null;

    @JsonProperty("name")
    private Name name = null;

    @JsonProperty("phone_number")
    private Phone phoneNumber = null;

    @JsonProperty("relationship")
    private String relationship = null;

    @JsonProperty("years_known")
    private String yearsKnown = null;

   

}
