/*
 * Ability Options LLC App
 * This servers hosts API needed for Ability Options LLC.
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.ability.model;

import java.util.List;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

@JsonInclude(Include. NON_NULL)
@AllArgsConstructor
@NoArgsConstructor
@Data
@ToString
public class TaskReviewInfo {

    @JsonProperty("activity_living")
    private List<KeyValuePair> activityLiving = null;

    @JsonProperty("habitation")
    private List<KeyValuePair> habitation = null;

    @JsonProperty("assisting_with")
    private List<KeyValuePair> assistingWith = null;

    @JsonProperty("night_shift_details")
    private List<KeyValuePair> nightShiftDetails = null;

}
